### ISSUE TITLE
USB stack in Nim?

### ISSUE THREAD

**Issue by dumblob** [PMunch/badger#3]
I'm currently working on an esoteric keyboard for smartphones and saw your videos about your cool and simple firmware. I'd use it but I didn't have time to evaluate all the pros & cons yet.

Anyway I wonder whether you plan to make it work on Teensy 2.x devices (i.e. those pretty old ones) **without** including any USB code written in C?

**Comment by PMunch** [comment]
The device I use in the videos is a Teensy 2.0, so it already works fine on that. And if you watch the unlisted videos (linked to from the description of the edited videos) you can see me in [episode 6](https://www.youtube.com/watch?v=vbQ_gciovwI) and [7](https://www.youtube.com/watch?v=QPxlh6t9Myw) rewriting the C library in Nim so that the actual code is now 100% Nim. If you have a look at the `final` branch of this repo you can see the most up-to-date code for this project.

**Comment by dumblob** [comment]
Perfect! I'll then probably give the uC from Teensy 2.x a go and if I have some issues, I'll come back here :wink:.

The branch `final` looks promising. Keep at it!

**Comment by PMunch** [comment]
I also plan on trying to get it to work on even smaller micro-controllers, the Attiny85 being my primary target for that.
